amcl:
  ros__parameters:
    base_frame_id: "robotinobase4/base_link"
    odom_frame_id: "robotinobase4/odom"
    scan_topic: /robotinobase4/scan

bt_navigator:
  ros__parameters:
    robot_base_frame: robotinobase4/base_link
    odom_topic: "/robotinobase4/odom_filtered"

controller_server:
  ros__parameters:
    odom_topic: "/robotinobase4/odom_filtered"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robotinobase4/odom
      robot_base_frame: robotinobase4/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase4/scan

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: robotinobase4/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase4/scan

map_server:
  ros__parameters:
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:

planner_server:
  ros__parameters:

behavior_server:
  ros__parameters:
    # costmap_topic: /robotinobase4/local_costmap/costmap_raw
    # footprint_topic: /robotinobase4/local_costmap/published_footprint
    local_costmap_topic: /robotinobase4/local_costmap/costmap_raw
    global_costmap_topic: /robotinobase4/global_costmap/costmap_raw
    local_footprint_topic: /robotinobase4/local_costmap/published_footprint
    global_footprint_topic: /robotinobase4/global_costmap/published_footprint
    robot_base_frame: robotinobase4/base_link
    local_frame: robotinobase4/odom

velocity_smoother:
  ros__parameters:
    odom_topic: "/robotinobase4/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "robotinobase4/base_link"
    odom_frame_id: "robotinobase4/odom"
    cmd_vel_in_topic: "/robotinobase4/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase4/cmd_vel"
    state_topic: "/robotinobase4/cm_state"
    PolygonStop:
      polygon_pub_topic: "/robotinobase4/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/robotinobase4/polygon_slowdown"
    scan:
      topic: "/robotinobase4/irsensor_scan"
