amcl:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    scan_topic: /robotinobase3/scan
    initial_pose:
      x: 4.5
      y: 0.45
      z: 0.0
      yaw: 3.14

bt_navigator:
  ros__parameters:
    robot_base_frame: robotinobase3/base_link
    odom_topic: "/robotinobase3/odom_filtered"

controller_server:
  ros__parameters:
    odom_topic: "/robotinobase3/odom_filtered"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robotinobase3/odom
      robot_base_frame: robotinobase3/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase3/scan

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: robotinobase3/base_link
      obstacle_layer:
        scan:
          topic: /robotinobase3/scan

map_server:
  ros__parameters:
    yaml_filename: "/home/srb-jarvis/ros2_ws/ws_thesis/simulation_ws/src/rcll_simulation_webots/robotino3_navigation/map/map.yaml"

map_saver:
  ros__parameters:

planner_server:
  ros__parameters:

behavior_server:
  ros__parameters:
    costmap_topic: /robotinobase3/local_costmap/costmap_raw
    # footprint_topic: /robotinobase3/local_costmap/published_footprint
    robot_base_frame: robotinobase3/base_link

velocity_smoother:
  ros__parameters:
    odom_topic: "/robotinobase3/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    cmd_vel_in_topic: "/robotinobase3/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase3/cmd_vel"
    state_topic: "/robotinobase3/cm_state"
    PolygonStop:
      polygon_pub_topic: "/robotinobase3/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/robotinobase3/polygon_slowdown"
    scan:
      topic: "/robotinobase3/irsensor_scan"
