amcl:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    scan_topic: /robotinobase3/scan
    initial_pose:
      x: 4.5
      y: 0.45
      z: 0.0
      yaw: 3.14

bt_navigator:
  ros__parameters:
    robot_base_frame: robotinobase3/base_link
    odom_topic: "/robotinobase3/odom_filtered"

controller_server:
  ros__parameters:
    odom_topic: "/robotinobase3/odom_filtered"

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robotinobase3/odom
      robot_base_frame: robotinobase3/base_link
      obstacle_layer:
        scan_lidar:
          topic: /robotinobase3/scan
          sensor_frame: robotinobase3/laser_link
        scan_ir:
          topic: /robotinobase3/irsensor_scan
          sensor_frame: robotinobase3/irscan_link
      keepout_filter:
        filter_info_topic: "/robotinobase3/costmap_filter_info"

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: robotinobase3/base_link
      static_layer:
        map_topic: /map
      obstacle_layer:
        scan:
          topic: /robotinobase3/scan
          sensor_frame: robotinobase3/laser_link
      keepout_filter:
        filter_info_topic: "/robotinobase1/costmap_filter_info"

costmap_filter_info_server:
  ros__parameters:
    filter_info_topic: "/robotinobase1/costmap_filter_info"
    mask_topic: "/robotinobase1/keepout_filter_mask"

filter_mask_server:
  ros__parameters:
    topic_name: "/robotinobase1/keepout_filter_mask"
    yaml_filename: "filter_mask.yaml"

map_server:
  ros__parameters:
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:

planner_server:
  ros__parameters:

behavior_server:
  ros__parameters:
    # costmap_topic: /robotinobase3/local_costmap/costmap_raw
    # footprint_topic: /robotinobase3/local_costmap/published_footprint
    local_costmap_topic: /robotinobase3/local_costmap/costmap_raw
    global_costmap_topic: /robotinobase3/global_costmap/costmap_raw
    local_footprint_topic: /robotinobase3/local_costmap/published_footprint
    global_footprint_topic: /robotinobase3/global_costmap/published_footprint
    robot_base_frame: robotinobase3/base_link
    local_frame: robotinobase3/odom

velocity_smoother:
  ros__parameters:
    odom_topic: "/robotinobase3/odom_filtered"

collision_monitor:
  ros__parameters:
    base_frame_id: "robotinobase3/base_link"
    odom_frame_id: "robotinobase3/odom"
    cmd_vel_in_topic: "/robotinobase3/cmd_vel_smoothed"
    cmd_vel_out_topic: "/robotinobase3/cmd_vel"
    state_topic: "/robotinobase3/cm_state"
    PolygonStop:
      polygon_pub_topic: "/robotinobase3/polygon_stop"
    PolygonSlow:
      polygon_pub_topic: "/robotinobase3/polygon_slowdown"
    scan:
      topic: "/robotinobase3/irsensor_scan"
